<?php
// database/seeders/ApprovalWorkflowSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApprovalWorkflowSeeder extends Seeder
{
  public function run(): void
  {
    // Clear existing workflows
    DB::table('approval_workflows')->truncate();

    // Get first user ID or use NULL
    $userId = DB::table('users')->value('id') ?? null;

    // ============================================
    // 1. DEFAULT WORKFLOW - 4-LEVEL APPROVAL
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'Standard 4-Level Approval',
      'description' => 'Complete 4-level approval workflow: HOD → Accountant → Principal → Final Approver',
      'department_id' => null,
      'min_amount' => 0,
      'max_amount' => null,
      'approval_levels' => json_encode([
        [
          'level' => 'hod',
          'order' => 1,
          'required' => true,
          'description' => 'Head of Department Approval',
        ],
        [
          'level' => 'accountant',
          'order' => 2,
          'required' => true,
          'description' => 'Accountant Verification & Approval',
        ],
        [
          'level' => 'principal',
          'order' => 3,
          'required' => true,
          'description' => 'Principal/Head of Institution Approval',
        ],
        [
          'level' => 'final',
          'order' => 4,
          'required' => true,
          'description' => 'Final Approver (Director/Education Secretary)',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 24,
        'reminder_hours' => 12,
        'escalation_hours' => 48,
        'allow_override' => false,
        'allow_reassignment' => true,
        'allow_skip' => false,
        'allow_revision' => true,
        'max_revisions' => 3,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => true,
        'require_quotation' => true,
        'min_items' => 1,
        'max_items' => 100,
        'require_description' => true,
        'require_justification' => true,
      ]),
      'is_active' => 1,
      'is_default' => 1,
      'threshold_level_1' => 0,
      'threshold_level_2' => 100000,
      'threshold_level_3' => 500000,
      'required_approvals' => 4,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 24,
      'reminder_hours' => 12,
      'escalation_hours' => 48,
      'allow_override' => 0,
      'allow_reassignment' => 1,
      'allow_skip' => 0,
      'allow_revision' => 1,
      'max_revisions' => 3,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    // ============================================
    // 2. SMALL AMOUNT WORKFLOW (Under 50,000)
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'Small Amount Approval (Under 50K)',
      'description' => 'Simplified 2-level approval for small value requisitions',
      'department_id' => null,
      'min_amount' => 0,
      'max_amount' => 50000,
      'approval_levels' => json_encode([
        [
          'level' => 'hod',
          'order' => 1,
          'required' => true,
          'description' => 'Head of Department Approval',
        ],
        [
          'level' => 'accountant',
          'order' => 2,
          'required' => true,
          'description' => 'Accountant Verification & Approval',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 12,
        'reminder_hours' => 6,
        'escalation_hours' => 24,
        'allow_override' => false,
        'allow_reassignment' => true,
        'allow_skip' => false,
        'allow_revision' => true,
        'max_revisions' => 2,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => true,
        'require_quotation' => false,
        'min_items' => 1,
        'max_items' => 50,
        'require_description' => true,
        'require_justification' => true,
      ]),
      'is_active' => 1,
      'is_default' => 0,
      'threshold_level_1' => 0,
      'threshold_level_2' => 25000,
      'threshold_level_3' => 50000,
      'required_approvals' => 2,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 12,
      'reminder_hours' => 6,
      'escalation_hours' => 24,
      'allow_override' => 0,
      'allow_reassignment' => 1,
      'allow_skip' => 0,
      'allow_revision' => 1,
      'max_revisions' => 2,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    // ============================================
    // 3. MEDIUM AMOUNT WORKFLOW (50,000 - 500,000)
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'Medium Amount Approval (50K - 500K)',
      'description' => '3-level approval for medium value requisitions',
      'department_id' => null,
      'min_amount' => 50000,
      'max_amount' => 500000,
      'approval_levels' => json_encode([
        [
          'level' => 'hod',
          'order' => 1,
          'required' => true,
          'description' => 'Head of Department Approval',
        ],
        [
          'level' => 'accountant',
          'order' => 2,
          'required' => true,
          'description' => 'Accountant Verification & Approval',
        ],
        [
          'level' => 'principal',
          'order' => 3,
          'required' => true,
          'description' => 'Principal/Head of Institution Approval',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 18,
        'reminder_hours' => 8,
        'escalation_hours' => 36,
        'allow_override' => false,
        'allow_reassignment' => true,
        'allow_skip' => false,
        'allow_revision' => true,
        'max_revisions' => 2,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => true,
        'require_quotation' => true,
        'min_items' => 1,
        'max_items' => 75,
        'require_description' => true,
        'require_justification' => true,
      ]),
      'is_active' => 1,
      'is_default' => 0,
      'threshold_level_1' => 50000,
      'threshold_level_2' => 200000,
      'threshold_level_3' => 500000,
      'required_approvals' => 3,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 18,
      'reminder_hours' => 8,
      'escalation_hours' => 36,
      'allow_override' => 0,
      'allow_reassignment' => 1,
      'allow_skip' => 0,
      'allow_revision' => 1,
      'max_revisions' => 2,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    // ============================================
    // 4. LARGE AMOUNT WORKFLOW (Above 500,000)
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'Large Amount Approval (Above 500K)',
      'description' => 'Full 4-level approval with enhanced oversight for high value requisitions',
      'department_id' => null,
      'min_amount' => 500000,
      'max_amount' => null,
      'approval_levels' => json_encode([
        [
          'level' => 'hod',
          'order' => 1,
          'required' => true,
          'description' => 'Head of Department Approval',
        ],
        [
          'level' => 'accountant',
          'order' => 2,
          'required' => true,
          'description' => 'Accountant Verification & Approval',
        ],
        [
          'level' => 'principal',
          'order' => 3,
          'required' => true,
          'description' => 'Principal/Head of Institution Approval',
        ],
        [
          'level' => 'final',
          'order' => 4,
          'required' => true,
          'description' => 'Final Approver (Director/Education Secretary)',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 24,
        'reminder_hours' => 12,
        'escalation_hours' => 48,
        'allow_override' => false,
        'allow_reassignment' => true,
        'allow_skip' => false,
        'allow_revision' => true,
        'max_revisions' => 3,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => true,
        'require_quotation' => true,
        'min_items' => 1,
        'max_items' => 100,
        'require_description' => true,
        'require_justification' => true,
        'require_tender' => true,
      ]),
      'is_active' => 1,
      'is_default' => 0,
      'threshold_level_1' => 500000,
      'threshold_level_2' => 1000000,
      'threshold_level_3' => 5000000,
      'required_approvals' => 4,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 24,
      'reminder_hours' => 12,
      'escalation_hours' => 48,
      'allow_override' => 0,
      'allow_reassignment' => 1,
      'allow_skip' => 0,
      'allow_revision' => 1,
      'max_revisions' => 3,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    // ============================================
    // 5. EMERGENCY WORKFLOW (Fast-Track)
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'Emergency/Fast-Track Approval',
      'description' => 'Expedited approval for emergency requisitions',
      'department_id' => null,
      'min_amount' => 0,
      'max_amount' => null,
      'approval_levels' => json_encode([
        [
          'level' => 'accountant',
          'order' => 1,
          'required' => true,
          'description' => 'Accountant Verification',
        ],
        [
          'level' => 'principal',
          'order' => 2,
          'required' => true,
          'description' => 'Principal/Head of Institution Approval',
        ],
        [
          'level' => 'final',
          'order' => 3,
          'required' => true,
          'description' => 'Final Approver (Director/Education Secretary)',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 2,
        'reminder_hours' => 1,
        'escalation_hours' => 4,
        'allow_override' => true,
        'allow_reassignment' => true,
        'allow_skip' => true,
        'allow_revision' => false,
        'max_revisions' => 1,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => true,
        'require_quotation' => false,
        'min_items' => 1,
        'max_items' => 50,
        'require_description' => true,
        'require_justification' => true,
        'is_emergency' => true,
      ]),
      'is_active' => 1,
      'is_default' => 0,
      'threshold_level_1' => 0,
      'threshold_level_2' => 0,
      'threshold_level_3' => 0,
      'required_approvals' => 3,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 2,
      'reminder_hours' => 1,
      'escalation_hours' => 4,
      'allow_override' => 1,
      'allow_reassignment' => 1,
      'allow_skip' => 1,
      'allow_revision' => 0,
      'max_revisions' => 1,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    // ============================================
    // 6. HOD ONLY WORKFLOW (Very Small Amounts)
    // ============================================
    DB::table('approval_workflows')->insert([
      'name' => 'HOD Only Approval (Under 10K)',
      'description' => 'Single-level approval for very small value requisitions',
      'department_id' => null,
      'min_amount' => 0,
      'max_amount' => 10000,
      'approval_levels' => json_encode([
        [
          'level' => 'hod',
          'order' => 1,
          'required' => true,
          'description' => 'Head of Department Approval',
        ],
      ]),
      'rules' => json_encode([
        'require_sequential' => true,
        'require_all_approvals' => true,
        'allow_delegation' => true,
        'max_approvers' => 1,
        'sla_hours' => 8,
        'reminder_hours' => 4,
        'escalation_hours' => 16,
        'allow_override' => false,
        'allow_reassignment' => true,
        'allow_skip' => false,
        'allow_revision' => true,
        'max_revisions' => 2,
        'require_justification_for_revision' => true,
        'auto_approve_after_revision' => false,
      ]),
      'conditions' => json_encode([
        'require_budget_check' => false,
        'require_quotation' => false,
        'min_items' => 1,
        'max_items' => 20,
        'require_description' => true,
        'require_justification' => false,
      ]),
      'is_active' => 1,
      'is_default' => 0,
      'threshold_level_1' => 0,
      'threshold_level_2' => 5000,
      'threshold_level_3' => 10000,
      'required_approvals' => 1,
      'require_all_approvals' => 1,
      'allow_delegation' => 1,
      'allow_parallel_approvals' => 0,
      'require_sequential' => 1,
      'max_approvers' => 1,
      'sla_hours' => 8,
      'reminder_hours' => 4,
      'escalation_hours' => 16,
      'allow_override' => 0,
      'allow_reassignment' => 1,
      'allow_skip' => 0,
      'allow_revision' => 1,
      'max_revisions' => 2,
      'require_justification_for_revision' => 1,
      'auto_approve_after_revision' => 0,
      'created_by' => $userId,
      'updated_by' => $userId,
      'created_at' => now(),
      'updated_at' => now(),
    ]);

    $this->command->info('✅ Approval workflows seeded successfully!');
    $this->command->info('📋 6 workflows created:');
    $this->command->info('  1. Standard 4-Level Approval (Default)');
    $this->command->info('  2. Small Amount Approval (Under 50K)');
    $this->command->info('  3. Medium Amount Approval (50K - 500K)');
    $this->command->info('  4. Large Amount Approval (Above 500K)');
    $this->command->info('  5. Emergency/Fast-Track Approval');
    $this->command->info('  6. HOD Only Approval (Under 10K)');
  }
}
