<?php
// app/Http/Resources/Procurement/PurchaseOrderResource.php

declare(strict_types=1);

namespace App\Http\Resources\Procurement;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Log;

class PurchaseOrderResource extends JsonResource
{
  public function toArray(Request $request): array
  {
    return [
      'id' => $this->id,
      'requisition_id' => $this->requisition_id,
      'supplier_id' => $this->supplier_id,
      'supplier_quotation_id' => $this->supplier_quotation_id,
      'po_number' => $this->po_number,
      'type' => $this->type,
      'type_label' => $this->type_label,
      'type_color' => $this->type_color,
      'is_lpo' => $this->is_lpo,
      'is_lso' => $this->is_lso,
      'title' => $this->title,
      'description' => $this->description,
      'total_amount' => $this->total_amount,
      'formatted_total_amount' => $this->formatted_total_amount,
      'tax_amount' => $this->tax_amount,
      'total_with_tax' => $this->total_with_tax,
      'currency' => $this->currency,
      'issue_date' => $this->formatDate($this->issue_date),
      'expected_delivery_date' => $this->formatDate($this->expected_delivery_date),
      'actual_delivery_date' => $this->formatDate($this->actual_delivery_date),
      'delivery_address' => $this->delivery_address,
      'delivery_contact' => $this->delivery_contact,
      'delivery_phone' => $this->delivery_phone,
      'delivery_email' => $this->delivery_email,
      'payment_terms' => $this->payment_terms,
      'delivery_terms' => $this->delivery_terms,
      'special_conditions' => $this->special_conditions,
      'terms_and_conditions' => $this->terms_and_conditions,
      'validity_period_days' => $this->validity_period_days,
      'contract_number' => $this->contract_number,
      'contract_start_date' => $this->formatDate($this->contract_start_date),
      'contract_end_date' => $this->formatDate($this->contract_end_date),
      'status' => $this->status,
      'status_label' => $this->status_label,
      'status_color' => $this->status_color,
      'is_overdue' => $this->is_overdue,
      'delivery_progress' => $this->delivery_progress,
      'is_fully_delivered' => $this->is_fully_delivered,
      'can_be_modified' => $this->can_be_modified,

      // ✅ Generated By
      'generated_by' => $this->generated_by,
      'generated_by_user' => $this->whenLoaded('generatedBy', function () {
        return $this->formatUser($this->generatedBy);
      }),

      // ✅ Checked By
      'checked_by' => $this->checked_by,
      'checked_by_user' => $this->whenLoaded('checkedBy', function () {
        return $this->formatUser($this->checkedBy);
      }),
      'checked_at' => $this->formatDateTime($this->checked_at),

      // ✅ Endorsed By
      'endorsed_by' => $this->endorsed_by,
      'endorsed_by_user' => $this->whenLoaded('endorsedBy', function () {
        return $this->formatUser($this->endorsedBy);
      }),
      'endorsed_at' => $this->formatDateTime($this->endorsed_at),

      // ✅ Approved By
      'approved_by' => $this->approved_by,
      'approved_by_user' => $this->whenLoaded('approvedBy', function () {
        return $this->formatUser($this->approvedBy);
      }),
      'approved_at' => $this->formatDateTime($this->approved_at),

      // ✅ Download tracking fields
      'download_count' => (int) ($this->download_count ?? 0),
      'last_downloaded_at' => $this->formatDateTime($this->last_downloaded_at),
      'pdf_storage_path' => $this->pdf_storage_path,
      'pdf_filename' => $this->pdf_filename,
      'pdf_upload_id' => $this->pdf_upload_id,

      // ✅ Upload data
      'upload' => $this->whenLoaded('pdfUpload', function () {
        return $this->formatUploadData($this->pdfUpload);
      }),

      // ✅ Supplier data
      'supplier' => $this->whenLoaded('supplier', function () {
        return $this->formatSupplier($this->supplier);
      }, [
        'id' => null,
        'name' => $this->supplier_name,
        'email' => null,
        'phone' => null,
      ]),

      // ✅ Purchase Order Items
      'items' => $this->whenLoaded('items', function () {
        return $this->items->map(function ($item) {
          return $this->formatItem($item);
        });
      }),

      // ✅ FULL REQUISITION INFORMATION (WITH ITEMS)
      'requisition' => $this->whenLoaded('requisition', function () {
        return $this->formatRequisition($this->requisition);
      }),

      // ✅ Approvals summary
      'approvals' => [
        'generated_by' => $this->generatedBy?->full_name,
        'generated_at' => $this->formatDateTime($this->created_at),
        'checked_by' => $this->checkedBy?->full_name,
        'checked_at' => $this->formatDateTime($this->checked_at),
        'endorsed_by' => $this->endorsedBy?->full_name,
        'endorsed_at' => $this->formatDateTime($this->endorsed_at),
        'approved_by' => $this->approvedBy?->full_name,
        'approved_at' => $this->formatDateTime($this->approved_at),
      ],

      // ✅ Timeline
      'timeline' => [
        'generated_at' => $this->formatDateTime($this->created_at),
        'issued_at' => $this->formatDateTime($this->issued_at),
        'sent_at' => $this->formatDateTime($this->sent_at),
        'acknowledged_at' => $this->formatDateTime($this->acknowledged_at),
        'delivered_at' => $this->formatDateTime($this->actual_delivery_date),
        'completed_at' => $this->formatDateTime($this->completed_at),
      ],

      // ✅ Digital Signatures
      'digital_signatures' => [
        'generator' => $this->digital_signature_generator,
        'checker' => $this->digital_signature_checker,
        'endorser' => $this->digital_signature_endorser,
        'approver' => $this->digital_signature_approver,
      ],

      // ✅ Metadata
      'metadata' => $this->metadata,

      'created_at' => $this->formatDateTime($this->created_at),
      'updated_at' => $this->formatDateTime($this->updated_at),
    ];
  }

  /**
   * Format a user for response
   */
  private function formatUser($user): ?array
  {
    if (!$user) {
      return null;
    }

    return [
      'id' => $user->id,
      'full_name' => $user->full_name ?? $user->first_name . ' ' . $user->last_name,
      'first_name' => $user->first_name,
      'last_name' => $user->last_name,
      'email' => $user->email,
      'phone' => $user->phone,
      'role' => $user->getPrimaryRole()?->name ?? $user->roles->first()?->name ?? null,
      'role_label' => $user->role_label ?? $user->getPrimaryRole()?->label ?? null,
      'avatar_url' => $user->avatar_url,
      'department_id' => $user->department_id,
      'department' => $user->department ? [
        'id' => $user->department->id,
        'name' => $user->department->name,
        'code' => $user->department->code,
      ] : null,
    ];
  }

  /**
   * Format a supplier for response
   */
  private function formatSupplier($supplier): ?array
  {
    if (!$supplier) {
      return null;
    }

    return [
      'id' => $supplier->id,
      'name' => $supplier->full_name ?? $supplier->company_name,
      'full_name' => $supplier->full_name,
      'company_name' => $supplier->company_name,
      'email' => $supplier->email,
      'company_email' => $supplier->company_email,
      'phone' => $supplier->phone,
      'company_phone' => $supplier->company_phone,
      'company_address' => $supplier->company_address,
      'company_registration' => $supplier->company_registration,
      'tax_id' => $supplier->tax_id,
      'category' => $supplier->category,
      'category_label' => $supplier->category_label,
      'status' => $supplier->status,
      'status_label' => $supplier->status_label,
      'is_active' => $supplier->is_active,
      'is_blacklisted' => $supplier->is_blacklisted,
      'contact_person_name' => $supplier->contact_person_name,
      'contact_person_email' => $supplier->contact_person_email,
      'contact_person_phone' => $supplier->contact_person_phone,
      'bank_name' => $supplier->bank_name,
      'bank_branch' => $supplier->bank_branch,
      'bank_account' => $supplier->bank_account,
      'preferred_currency' => $supplier->preferred_currency,
      'created_at' => $this->formatDateTime($supplier->created_at),
      'updated_at' => $this->formatDateTime($supplier->updated_at),
    ];
  }

  /**
   * Format a purchase order item for response
   */
  private function formatItem($item): array
  {
    return [
      'id' => $item->id,
      'purchase_order_id' => $item->purchase_order_id,
      'requisition_item_id' => $item->requisition_item_id,
      'supplier_quotation_item_id' => $item->supplier_quotation_item_id,
      'item_name' => $item->item_name,
      'description' => $item->description,
      'unit_of_measure' => $item->unit_of_measure,
      'quantity' => $item->quantity,
      'formatted_quantity' => $item->formatted_quantity,
      'unit_price' => $item->unit_price,
      'formatted_unit_price' => $item->formatted_unit_price,
      'total_price' => $item->total_price,
      'formatted_total_price' => $item->formatted_total_price,
      'tax_rate' => $item->tax_rate,
      'tax_amount' => $item->tax_amount,
      'discount_rate' => $item->discount_rate,
      'discount_amount' => $item->discount_amount,
      'net_price' => $item->net_price,
      'formatted_net_price' => $item->formatted_net_price,
      'delivery_days' => $item->delivery_days,
      'warranty_months' => $item->warranty_months,
      'specifications' => $item->specifications,
      'brand' => $item->brand,
      'model' => $item->model,
      'catalog_number' => $item->catalog_number,
      'received_quantity' => $item->received_quantity,
      'formatted_received_quantity' => $item->formatted_received_quantity,
      'remaining_quantity' => $item->remaining_quantity,
      'formatted_remaining_quantity' => $item->formatted_remaining_quantity,
      'accepted_quantity' => $item->accepted_quantity,
      'rejected_quantity' => $item->rejected_quantity,
      'fully_received' => $item->fully_received,
      'fully_received_at' => $this->formatDateTime($item->fully_received_at),
      'status' => $item->status,
      'status_label' => $item->status_label,
      'status_color' => $item->status_color,
      'is_fully_received' => $item->is_fully_received,
      'notes' => $item->notes,
      'metadata' => $item->metadata,
      'created_at' => $this->formatDateTime($item->created_at),
      'updated_at' => $this->formatDateTime($item->updated_at),
    ];
  }

  /**
   * ✅ Format full requisition information WITH ITEMS
   */
  private function formatRequisition($requisition): array
  {
    if (!$requisition) {
      return [];
    }

    // ✅ Get requisition items if loaded
    $requisitionItems = [];
    if ($requisition->relationLoaded('items') && $requisition->items) {
      $requisitionItems = $requisition->items->map(function ($item) {
        return $this->formatRequisitionItem($item);
      })->toArray();
    }

    return [
      // Basic Information
      'id' => $requisition->id,
      'reference_number' => $requisition->reference_number,
      'title' => $requisition->title,
      'description' => $requisition->description,
      'status' => $requisition->status,
      'status_label' => $requisition->status_label,
      'status_color' => $requisition->status_color,

      // Priority & Type
      'priority' => $requisition->priority,
      'priority_label' => $requisition->priority_label,
      'priority_color' => $requisition->priority_color,
      'type' => $requisition->type,
      'type_label' => $requisition->type_label,
      'urgency' => $requisition->urgency,
      'urgency_label' => $requisition->urgency_label,

      // Financial
      'total_amount' => $requisition->total_amount,
      'formatted_total_amount' => number_format((float) $requisition->total_amount, 2),
      'currency' => $requisition->currency ?? 'KES',
      'budget_allocated' => $requisition->budget_allocated,
      'budget_utilized' => $requisition->budget_utilized,
      'budget_code' => $requisition->budget_code,
      'budget_source' => $requisition->budget_source,
      'funding_source' => $requisition->funding_source,
      'project_code' => $requisition->project_code,

      // Dates
      'submitted_at' => $this->formatDateTime($requisition->submitted_at),
      'required_by_date' => $this->formatDate($requisition->required_by_date),
      'required_delivery_date' => $this->formatDate($requisition->required_delivery_date),

      // Approval Dates
      'hod_approved_at' => $this->formatDateTime($requisition->hod_approved_at),
      'hod_declined_at' => $this->formatDateTime($requisition->hod_declined_at),
      'hod_decline_reason' => $requisition->hod_decline_reason,
      'accountant_approved_at' => $this->formatDateTime($requisition->accountant_approved_at),
      'accountant_declined_at' => $this->formatDateTime($requisition->accountant_declined_at),
      'accountant_decline_reason' => $requisition->accountant_decline_reason,
      'principal_approved_at' => $this->formatDateTime($requisition->principal_approved_at),
      'principal_declined_at' => $this->formatDateTime($requisition->principal_declined_at),
      'principal_decline_reason' => $requisition->principal_decline_reason,
      'final_approved_at' => $this->formatDateTime($requisition->final_approved_at),
      'final_declined_at' => $this->formatDateTime($requisition->final_declined_at),
      'final_decline_reason' => $requisition->final_decline_reason,
      'last_approval_at' => $this->formatDateTime($requisition->last_approval_at),

      // Return Information
      'returned_at' => $this->formatDateTime($requisition->returned_at),
      'return_reason' => $requisition->return_reason,
      'returned_by' => $requisition->returned_by,
      'return_count' => $requisition->return_count,

      // User Information
      'user_id' => $requisition->user_id,
      'user' => $requisition->user ? [
        'id' => $requisition->user->id,
        'full_name' => $requisition->user->full_name,
        'first_name' => $requisition->user->first_name,
        'last_name' => $requisition->user->last_name,
        'email' => $requisition->user->email,
        'role_label' => $requisition->user->role_label,
      ] : null,
      'submitted_by' => $requisition->submitted_by,

      // Department Information
      'department_id' => $requisition->department_id,
      'department' => $requisition->department ? [
        'id' => $requisition->department->id,
        'name' => $requisition->department->name,
        'code' => $requisition->department->code,
        'description' => $requisition->department->description,
        'hod_id' => $requisition->department->hod_id,
        'is_active' => $requisition->department->is_active,
      ] : null,

      // Supplier Information
      'supplier_id' => $requisition->supplier_id,
      'supplier' => $requisition->supplier ? [
        'id' => $requisition->supplier->id,
        'name' => $requisition->supplier->full_name ?? $requisition->supplier->company_name,
        'company_name' => $requisition->supplier->company_name,
      ] : null,

      // Procurement
      'is_procurement_created' => $requisition->is_procurement_created,
      'procurement_created_at' => $this->formatDateTime($requisition->procurement_created_at),
      'procurement_method' => $requisition->procurement_method,

      // Compliance & Risk
      'risk_level' => $requisition->risk_level,
      'risk_level_label' => $this->getRiskLevelLabel($requisition->risk_level),
      'risk_mitigation' => $requisition->risk_mitigation,
      'is_compliant' => $requisition->is_compliant,
      'compliance_notes' => $requisition->compliance_notes,

      // SLA
      'sla_started_at' => $this->formatDateTime($requisition->sla_started_at),
      'sla_target_at' => $this->formatDateTime($requisition->sla_target_at),
      'sla_status' => $requisition->sla_status,
      'sla_status_label' => $this->getSlaStatusLabel($requisition->sla_status),

      // Approval Metrics
      'approval_level_count' => $requisition->approval_level_count,
      'total_approval_levels' => $requisition->total_approval_levels,

      // Auditing
      'audit_trail_last_checked' => $this->formatDateTime($requisition->audit_trail_last_checked),
      'audit_status' => $requisition->audit_status,
      'audited_by' => $requisition->audited_by,

      // Revision
      'revision_count' => $requisition->revision_count,
      'last_revised_at' => $this->formatDateTime($requisition->last_revised_at),
      'last_revised_by' => $requisition->last_revised_by,
      'revision_notes' => $requisition->revision_notes,
      'revision_status' => $requisition->revision_status,

      // Custom Fields & Metadata
      'custom_fields' => $requisition->custom_fields,
      'metadata' => $requisition->metadata,

      // Timestamps
      'created_at' => $this->formatDateTime($requisition->created_at),
      'updated_at' => $this->formatDateTime($requisition->updated_at),
      'deleted_at' => $this->formatDateTime($requisition->deleted_at),

      // Flags
      'is_editable' => $requisition->is_editable ?? false,
      'is_approvable' => $requisition->is_approvable ?? false,
      'is_returnable' => $requisition->is_returnable ?? false,
      'can_be_revised' => $requisition->can_be_revised ?? false,

      // ✅ REQUISITION ITEMS (for comparison with LPO items)
      'items' => $requisitionItems,
      'items_count' => count($requisitionItems),
    ];
  }

  /**
   * ✅ Format a single requisition item for response
   * This allows comparison with PO items
   */
  private function formatRequisitionItem($item): array
  {
    return [
      'id' => $item->id,
      'requisition_id' => $item->requisition_id,
      'item_name' => $item->item_name,
      'description' => $item->description,
      'unit_of_measure' => $item->unit_of_measure,
      'quantity' => $item->quantity,
      'formatted_quantity' => number_format((float) $item->quantity, 2),
      'estimated_unit_cost' => $item->estimated_unit_cost,
      'formatted_unit_cost' => number_format((float) $item->estimated_unit_cost, 2),
      'total_cost' => $item->total_cost,
      'formatted_total_cost' => number_format((float) $item->total_cost, 2),
      'specifications' => $item->specifications,
      'catalog_number' => $item->catalog_number,
      'manufacturer' => $item->manufacturer,
      'model_number' => $item->model_number,
      'tax_rate' => $item->tax_rate,
      'tax_amount' => $item->tax_amount,
      'discount_percentage' => $item->discount_percentage,
      'discount_amount' => $item->discount_amount,
      'net_amount' => $item->net_amount,
      'budget_allocated' => $item->budget_allocated,
      'budget_line_item' => $item->budget_line_item,
      'is_inventory_item' => $item->is_inventory_item,
      'inventory_code' => $item->inventory_code,
      'expected_delivery_date' => $this->formatDate($item->expected_delivery_date),
      'actual_delivery_date' => $this->formatDate($item->actual_delivery_date),
      'is_delivered' => $item->is_delivered,
      'is_procured' => $item->is_procured,
      'procured_at' => $this->formatDateTime($item->procured_at),
      'status' => $item->status,
      'status_label' => $item->status_label,
      'status_color' => $item->status_color,
      'quality_status' => $item->quality_status,
      'quality_status_label' => $item->quality_status_label,
      'received_quantity' => $item->received_quantity,
      'remaining_quantity' => $item->remaining_quantity,
      'is_fully_received' => $item->is_fully_received,
      'warranty_period_months' => $item->warranty_period_months,
      'warranty_start_date' => $this->formatDate($item->warranty_start_date),
      'warranty_end_date' => $this->formatDate($item->warranty_end_date),
      'created_at' => $this->formatDateTime($item->created_at),
      'updated_at' => $this->formatDateTime($item->updated_at),
      'metadata' => $item->metadata,
    ];
  }

  /**
   * Format a date field safely
   */
  private function formatDate($value): ?string
  {
    if (!$value) {
      return null;
    }

    try {
      if (is_string($value)) {
        $timestamp = strtotime($value);
        if ($timestamp !== false) {
          return date('Y-m-d', $timestamp);
        }
        return $value;
      }

      if ($value instanceof \Carbon\Carbon) {
        return $value->toDateString();
      }

      if ($value instanceof \DateTime) {
        return $value->format('Y-m-d');
      }

      return null;
    } catch (\Exception $e) {
      Log::warning('[PurchaseOrderResource] Failed to format date', [
        'value' => $value,
        'error' => $e->getMessage(),
      ]);
      return null;
    }
  }

  /**
   * Format a datetime field safely
   */
  private function formatDateTime($value): ?string
  {
    if (!$value) {
      return null;
    }

    try {
      if (is_string($value)) {
        $timestamp = strtotime($value);
        if ($timestamp !== false) {
          return date('Y-m-d H:i:s', $timestamp);
        }
        return $value;
      }

      if ($value instanceof \Carbon\Carbon) {
        return $value->toDateTimeString();
      }

      if ($value instanceof \DateTime) {
        return $value->format('Y-m-d H:i:s');
      }

      return null;
    } catch (\Exception $e) {
      Log::warning('[PurchaseOrderResource] Failed to format datetime', [
        'value' => $value,
        'error' => $e->getMessage(),
      ]);
      return null;
    }
  }

  /**
   * Format upload data from the Upload model
   */
  private function formatUploadData($upload): ?array
  {
    if (!$upload) {
      return null;
    }

    $uploadedByUser = null;
    $uploadedByName = null;

    if ($upload->relationLoaded('uploadedBy') && $upload->uploadedBy) {
      $user = $upload->uploadedBy;
      $uploadedByUser = [
        'id' => $user->id,
        'full_name' => $user->full_name,
        'first_name' => $user->first_name,
        'last_name' => $user->last_name,
        'email' => $user->email,
        'role_label' => $user->role_label,
      ];
      $uploadedByName = $user->full_name;
    } elseif (!empty($upload->uploaded_by)) {
      try {
        $user = \App\Models\User::find($upload->uploaded_by);
        if ($user) {
          $uploadedByUser = [
            'id' => $user->id,
            'full_name' => $user->full_name,
            'first_name' => $user->first_name,
            'last_name' => $user->last_name,
            'email' => $user->email,
            'role_label' => $user->role_label,
          ];
          $uploadedByName = $user->full_name;
        } else {
          $uploadedByName = 'Unknown User (ID: ' . $upload->uploaded_by . ')';
        }
      } catch (\Exception $e) {
        $uploadedByName = 'Unknown User';
      }
    }

    return [
      'id' => $upload->id,
      'uploadable_type' => $upload->uploadable_type,
      'uploadable_id' => $upload->uploadable_id,
      'file_name' => $upload->file_name,
      'original_name' => $upload->original_name,
      'file_path' => $upload->file_path,
      'file_url' => $upload->file_url ?? $upload->url,
      'file_type' => $upload->file_type,
      'mime_type' => $upload->mime_type,
      'extension' => $upload->extension,
      'file_size' => $upload->file_size,
      'formatted_size' => $upload->formatted_size,
      'width' => $upload->width,
      'height' => $upload->height,
      'image_orientation' => $upload->image_orientation,
      'is_image' => $upload->is_image,
      'is_document' => $upload->file_type === 'document',
      'disk' => $upload->disk,
      'collection' => $upload->collection,
      'title' => $upload->title,
      'description' => $upload->description,
      'meta_data' => $upload->meta_data,
      'status' => $upload->status,
      'status_label' => $this->getUploadStatusLabel($upload->status),
      'uploaded_by' => $upload->uploaded_by,
      'uploaded_by_user' => $uploadedByUser,
      'uploaded_by_name' => $uploadedByName,
      'uploaded_at' => $this->formatDateTime($upload->uploaded_at),
      'created_at' => $this->formatDateTime($upload->created_at),
      'updated_at' => $this->formatDateTime($upload->updated_at),
    ];
  }

  /**
   * Get upload status label
   */
  private function getUploadStatusLabel(?string $status): string
  {
    $labels = [
      'completed' => 'Completed',
      'pending' => 'Pending',
      'processing' => 'Processing',
      'failed' => 'Failed',
      'deleted' => 'Deleted',
    ];

    return $labels[$status] ?? ucfirst($status ?? 'Unknown');
  }

  /**
   * Get risk level label
   */
  private function getRiskLevelLabel(?string $riskLevel): string
  {
    $labels = [
      'low' => 'Low Risk',
      'medium' => 'Medium Risk',
      'high' => 'High Risk',
      'critical' => 'Critical Risk',
    ];

    return $labels[$riskLevel] ?? ucfirst($riskLevel ?? 'Unknown');
  }

  /**
   * Get SLA status label
   */
  private function getSlaStatusLabel(?string $slaStatus): string
  {
    $labels = [
      'on_track' => 'On Track',
      'at_risk' => 'At Risk',
      'overdue' => 'Overdue',
      'completed' => 'Completed',
      'not_started' => 'Not Started',
    ];

    return $labels[$slaStatus] ?? ucfirst($slaStatus ?? 'Unknown');
  }
}
