<?php
// app/Http/Resources/Procurement/QuotationResource.php

declare(strict_types=1);

namespace App\Http\Resources\Procurement;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class QuotationResource extends JsonResource
{
  public function toArray(Request $request): array
  {
    return [
      'id' => $this->id,
      'requisition_id' => $this->requisition_id,
      'qtn_number' => $this->qtn_number,
      'title' => $this->title,
      'description' => $this->description,
      'issue_date' => $this->issue_date?->toDateString(),
      'closing_date' => $this->closing_date?->toDateString(),
      'closing_time' => $this->closing_time,
      'delivery_terms' => $this->delivery_terms,
      'payment_terms' => $this->payment_terms,
      'special_conditions' => $this->special_conditions,
      'instructions' => $this->instructions,
      'status' => $this->status,
      'status_label' => $this->status_label,
      'status_color' => $this->status_color,
      'is_automated' => $this->is_automated,
      'is_tender' => $this->is_tender,
      'tender_number' => $this->tender_number,
      'sent_to_suppliers' => $this->sent_to_suppliers,
      'responded_suppliers' => $this->responded_suppliers,
      'declined_suppliers' => $this->declined_suppliers,
      'response_count' => $this->response_count,
      'response_rate' => $this->response_rate,
      'is_expired' => $this->is_expired,
      'is_closing_soon' => $this->is_closing_soon,
      'reminder_days' => $this->reminder_days,
      'generated_by' => $this->generatedBy ? [
        'id' => $this->generatedBy->id,
        'full_name' => $this->generatedBy->full_name,
        'email' => $this->generatedBy->email,
        'first_name' => $this->generatedBy->first_name,
        'last_name' => $this->generatedBy->last_name,
        'role_label' => $this->generatedBy->role_label,
      ] : null,
      'generated_by_name' => $this->generatedBy?->full_name,
      'requisition' => $this->whenLoaded('requisition', function () {
        return [
          'id' => $this->requisition->id,
          'reference_number' => $this->requisition->reference_number,
          'title' => $this->requisition->title,
          'description' => $this->requisition->description,
          'total_amount' => $this->requisition->total_amount,
          'formatted_total_amount' => number_format((float) $this->requisition->total_amount, 2),
          'status' => $this->requisition->status,
          'status_label' => $this->requisition->status_label,
          'status_color' => $this->requisition->status_color,
          'priority' => $this->requisition->priority,
          'priority_label' => $this->requisition->priority_label,
          'type' => $this->requisition->type,
          'type_label' => $this->requisition->type_label,
          'urgency' => $this->requisition->urgency,
          'urgency_label' => $this->requisition->urgency_label,
          'justification' => $this->requisition->justification,
          'budget_code' => $this->requisition->budget_code,
          'budget_source' => $this->requisition->budget_source,
          'funding_source' => $this->requisition->funding_source,
          'project_code' => $this->requisition->project_code,
          'procurement_method' => $this->requisition->procurement_method,
          'risk_level' => $this->requisition->risk_level,
          'risk_level_label' => $this->requisition->risk_level_label,
          'is_compliant' => $this->requisition->is_compliant,
          'is_procurement_created' => $this->requisition->is_procurement_created,
          'procurement_created_at' => $this->requisition->procurement_created_at,
          'submitted_at' => $this->requisition->submitted_at,
          'approved_at' => $this->requisition->approved_at,
          'returned_at' => $this->requisition->returned_at,
          'return_count' => $this->requisition->return_count,
          'return_reason' => $this->requisition->return_reason,
          'is_editable' => $this->requisition->is_editable,
          'is_approvable' => $this->requisition->is_approvable,
          'is_returnable' => $this->requisition->is_returnable,
          'can_be_revised' => $this->requisition->can_be_revised,
          'created_at' => $this->requisition->created_at?->toDateTimeString(),
          'updated_at' => $this->requisition->updated_at?->toDateTimeString(),
          'user' => $this->requisition->user ? [
            'id' => $this->requisition->user->id,
            'full_name' => $this->requisition->user->full_name,
            'email' => $this->requisition->user->email,
            'first_name' => $this->requisition->user->first_name,
            'last_name' => $this->requisition->user->last_name,
            'role' => $this->requisition->user->role,
            'role_label' => $this->requisition->user->role_label,
          ] : null,
          'department' => $this->requisition->department ? [
            'id' => $this->requisition->department->id,
            'name' => $this->requisition->department->name,
            'code' => $this->requisition->department->code,
          ] : null,
          'supplier' => $this->requisition->supplier ? [
            'id' => $this->requisition->supplier->id,
            'company_name' => $this->requisition->supplier->company_name,
          ] : null,
          'items' => $this->requisition->items ? $this->requisition->items->map(function ($item) {
            return [
              'id' => $item->id,
              'item_name' => $item->item_name,
              'description' => $item->description,
              'unit_of_measure' => $item->unit_of_measure,
              'quantity' => $item->quantity,
              'estimated_unit_cost' => $item->estimated_unit_cost,
              'total_cost' => $item->total_cost,
              'specifications' => $item->specifications,
              'catalog_number' => $item->catalog_number,
              'manufacturer' => $item->manufacturer,
              'model_number' => $item->model_number,
              'tax_rate' => $item->tax_rate,
              'discount_percentage' => $item->discount_percentage,
              'is_inventory_item' => $item->is_inventory_item,
              'inventory_code' => $item->inventory_code,
              'status' => $item->status,
              'status_label' => $item->status_label,
              'supplier' => $item->supplier ? [
                'id' => $item->supplier->id,
                'company_name' => $item->supplier->company_name,
              ] : null,
            ];
          }) : [],
          'approvals' => $this->requisition->approvals ? $this->requisition->approvals->map(function ($approval) {
            return [
              'id' => $approval->id,
              'level' => $approval->level,
              'level_label' => $approval->level_label,
              'status' => $approval->status,
              'status_label' => $approval->status_label,
              'comment' => $approval->comment,
              'reason' => $approval->reason,
              'is_delegated' => $approval->is_delegated,
              'reviewed_at' => $approval->reviewed_at?->toDateTimeString(),
              'due_date' => $approval->due_date?->toDateTimeString(),
              'approver' => $approval->approver ? [
                'id' => $approval->approver->id,
                'full_name' => $approval->approver->full_name,
                'email' => $approval->approver->email,
                'role' => $approval->approver->role,
                'role_label' => $approval->approver->role_label,
              ] : null,
              'delegate' => $approval->delegate ? [
                'id' => $approval->delegate->id,
                'full_name' => $approval->delegate->full_name,
                'role' => $approval->delegate->role,
                'role_label' => $approval->delegate->role_label,
              ] : null,
              'created_at' => $approval->created_at?->toDateTimeString(),
              'updated_at' => $approval->updated_at?->toDateTimeString(),
            ];
          }) : [],
          'metadata' => $this->requisition->metadata,
          'required_by_date' => $this->requisition->required_by_date,
          'required_delivery_date' => $this->requisition->required_delivery_date,
          'sla_status' => $this->requisition->sla_status,
          'sla_status_label' => $this->requisition->sla_status_label,
          'sla_started_at' => $this->requisition->sla_started_at,
          'sla_target_at' => $this->requisition->sla_target_at,
          'total_approval_levels' => $this->requisition->total_approval_levels,
          'approval_level_count' => $this->requisition->approval_level_count,
          'last_approval_at' => $this->requisition->last_approval_at?->toDateTimeString(),
          'estimated_completion_date' => $this->requisition->estimated_completion_date?->toDateString(),
          'currency' => $this->requisition->currency,
          'exchange_rate' => $this->requisition->exchange_rate,
          'total_amount_usd' => $this->requisition->total_amount_usd,
          'department_budget_balance' => $this->requisition->department_budget_balance,
          'department_utilization_percentage' => $this->requisition->department_utilization_percentage,
        ];
      }),
      'supplier_quotations' => $this->whenLoaded('supplierQuotations', function () {
        return SupplierQuotationResource::collection($this->supplierQuotations);
      }),
      'created_at' => $this->created_at?->toDateTimeString(),
      'updated_at' => $this->updated_at?->toDateTimeString(),
    ];
  }
}
